version: "3.3"
services:
  app:
    container_name: "sgbd"
    build:
      context: .
      dockerfile: php.dockerfile
    ports:
      - ${APP_EXTERNAL_PORT}:${APP_INTERNAL_PORT}
    volumes:
      - .:/var/www/html
    networks:
      - app

networks:
  app:
    driver: bridge
